# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lZgfcsj5vBS1piTzdA1g/F1pOgRV/IwmwwubasdnC2Qb/Ib4q/lAwMdgMmVlK8kA3fZ7iLIp+ZGumxz4R+SKKIFgVWSR/GGW0osG1v7NWoQN5aiCwHqn83skGn2AGy/mWbPqBGNKmIksHiq7iQCr6A+xEX6AK/lWhYG7zKNF3uSVR21n9E+jP2DpjYsnQb9yECZOlGZ+crjlnKikhzZwclOKrONnZdvW2vonJGAlLocctDHUezptv0UmcInpe2IplLpL8PXcN1tPbGh+ojvKAbsKmf1qYYJf5mD1iQvM0jmzKNVnGYwo9ISLG3SEWasCRhdj0BXcDHMckVOQB0+xTren/5AW9nzEw4/8b09/r//WincEJIO//CkRY+dYfapbUpXFsbhU0s2fD4hWkHFS6rF+5Hr3EQTAJAjBlJRS9Er6u8GBdTylcTwg+zY+GUCuqvOmgk/JAgBqpkruNxJ+XGhjT4/7ler9hgKLd8BZvJdXKaDRkXl6s1m+BFEzs7UY/2YfizyVMKt2RyRhngTOdWzOjjc4+4gtQaMmsemkMORuyPUL0+db3HM3BljwNwZI9JLW5OlLlfJuhYSmg/0GcF/mGyZpTAAy8tDKB5XhnBXQuKBZgr86ica1i2qdPIxjxVxUdDEi/xdEjxCNtxq1KM0wyJl5Mt4kb3zg1KzrbDA="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
