travis:
  secure:
    BINSTAR_TOKEN: rNlKm0ne+qnahM00ytf8JP7WdqscFMZpYZSM4LdpK3SmJPSL/mnlTGScN+Axoa4gcN/iR9qDGYNa8OBcq9rPM4FAq5O85wqzCklvq+Hcx1RHX+WbYfEHhGfomQtAXfp/WOc5XBIEZ/SECtmbokPjXPlX/wc4iOdwvVwcEaG4dOqj8Ay+ufkt448sMR4WsnLlR3jy/ZKMnu7YxJzoa6JWe0KQRJdXiwMJ7pBGktW0y864A/qHstfOF6cdenbO/Yb7hxClwEkmI5KLJiwO5TU+FkSdnW8/gG2zjkLcEMMqNvZhEpXJzuKBpztTsKKvqKdb8bzWM/HXgaZGIBBkXkOnn9HSQ4QqzweGMAOjRtUPqa/PqoDfYkXxLva5pHFSD0/KMhgFt3UC1g0wNIkPCLakX2UCNlFP3aBh+1fGsUbNKELjhnAwPJA7/GBqSGPTVLiT78K0z4syIL+xyuzdNlmOHY6N8i+h++1EnD49pM0KLCejkOPlsxZWrXCDrwBRi9IocqWVJqiEZRuywXa7CDuoghZ77tODWTxykt79lHsYMCZKgD7EZgJY+XjnKwFaOmLWkaYQR3rCHYTTTWKu6PDiIAXY5Yq8mPR8JAWz4DZ8vTgXlfscqXpGyANWouCJmPlrvU/Mo6Hzj7112UppviO6WX5x/JYrzfAy/87GuLayy94=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
