travis:
  secure:
    BINSTAR_TOKEN: E8z8al+fyl2xFFBl/U3sLoRmyvP1xnf0hZ1LChslYTQKE1oS3MqphmqbOPTep0gdGOE4HuGUjrNDI8iNZIzxje7sw2TZd1iN46sbnbjZ/2EHXpCJWlutP65sNGA+9+URcYrNIV20bO5YGgObg4SmU5pL1zfRmL4PTyItPViN7tND2+NCbTPmrM45Qs0MT+k5ypVQk6AqDhHDtRa88T+naQRD2Pszp/myDaXo4mwdu77yzn/T2gfxNAYqZUJLs684AULj7ldUNLA8P4lTmvucbeP7H1wR9NT8Fn6ssSoBd762PlyRRRpRIHq0MgwveanK3hkgguNzlUBP/fqaUavdvTwfTTdKxoPMDsBdYDfcsNK+l3pfhecXw/Ofi1w7fLXYsjzDQr/1xunK3rqJ0x7nhX9537B6hCot/Wp9NNfKokm+gY0fCVBxCqa1QQynHr9torShC/UhCSs+wl4xMfKJl/mAIuZqphL9a+pFiqQFhlulk/8KnSgyvdnPLTwXhwib1Y6NmCyvGy516c+9JBfxA6t+6qcGVfa+SHc590FpM0ga6Ya1cZzCR35Z01EROd2uT+7v4HxXkzn2RXEFmBEbL0VwB0KDEqdGBqhuisRJGgbSXTVBQfjVLE7uxo9W4ukVXTdcWK2LIIjdYsjDlaGYJbLczcw9HQgxWyK2/cMOtH4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
