travis:
  secure:
    BINSTAR_TOKEN: dO9gtyZEQXAwzmyLURujQ5IwGzWXmi7EaJgCPE1ODB1V2p52Sk+p4hW9qB2gjmtY6berrUpBhjyRLJULXp7aktDlYXXf+grkLWOeTpylxICATDAybmZ6SwI9wofcrTzTuyPY2pcMBbkDrQFhX0w5z5Uq8hLOa253g5RHIR4+hXd9hQPtegwPfDEU+xnS3KGx2blqoxoi8rHpQZnChGY2FUC3ekQMgzyLnlps1c6f3S+8iBEND1eWb5psVq3CjgA1IIZ1NokmU9JkZn0vkSBjS5GIO2pOj8kyGiSXBXL4dSJdi2TcnclE68rbLzYhNFd8EXd9X0cPVvbvLnTmQlbvTLt9OzzpLJ8sCzhkJiaRjLEB9egBECNCdwZr6EGo/VImCogqtup1r8TANh0GiibCaG3PP7rgVwb9JpKgzQIBCEuP6dy/CDga6QIUlO0eN1XbgaSloPAojjt1ekZE8dz73l6tKzpvNIiG1XHUrsA05Dv93YaFgAdtMJfWtiRO1svGvdx9BvIZJ8D3PVezKX9fqfqYbktYreYT6AQUY2VJdzWMU5lzZiPE1caPq8lv4BBUAEqcScs1LEKMrk5SkMupXOJ5Wzn1uS3W7Ld9OlBxnKa5yYLj4W7HXfimgSMOUD2+NWaxcIfeFvgp8+Z3oKFrfgjajPZe+Hp1GQus/siEemE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
