travis:
  secure:
    BINSTAR_TOKEN: lZgfcsj5vBS1piTzdA1g/F1pOgRV/IwmwwubasdnC2Qb/Ib4q/lAwMdgMmVlK8kA3fZ7iLIp+ZGumxz4R+SKKIFgVWSR/GGW0osG1v7NWoQN5aiCwHqn83skGn2AGy/mWbPqBGNKmIksHiq7iQCr6A+xEX6AK/lWhYG7zKNF3uSVR21n9E+jP2DpjYsnQb9yECZOlGZ+crjlnKikhzZwclOKrONnZdvW2vonJGAlLocctDHUezptv0UmcInpe2IplLpL8PXcN1tPbGh+ojvKAbsKmf1qYYJf5mD1iQvM0jmzKNVnGYwo9ISLG3SEWasCRhdj0BXcDHMckVOQB0+xTren/5AW9nzEw4/8b09/r//WincEJIO//CkRY+dYfapbUpXFsbhU0s2fD4hWkHFS6rF+5Hr3EQTAJAjBlJRS9Er6u8GBdTylcTwg+zY+GUCuqvOmgk/JAgBqpkruNxJ+XGhjT4/7ler9hgKLd8BZvJdXKaDRkXl6s1m+BFEzs7UY/2YfizyVMKt2RyRhngTOdWzOjjc4+4gtQaMmsemkMORuyPUL0+db3HM3BljwNwZI9JLW5OlLlfJuhYSmg/0GcF/mGyZpTAAy8tDKB5XhnBXQuKBZgr86ica1i2qdPIxjxVxUdDEi/xdEjxCNtxq1KM0wyJl5Mt4kb3zg1KzrbDA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
