travis:
  secure:
    BINSTAR_TOKEN: h3K3p7YUSwc4CmOCK0ziaro9gRqm5AUG8dgQRICHVFBDj4+TsdBUMSDcxNtt2rsn/oGsWrdrKKFr9bfKrqMsecNff9i0O++Bt97nZZARHXqnfswB4KjcNkE0kVNtvFBLfXljqQt+jUWYTkzKqlA1NKe/7t+zMdsZhqzSonamOHXHq0MarwoW1/N7lhMoLdTpFURxnXDTmyJ5zhk4ZSSB7tMSzZUX6KD1sbQGzaVhU48AV9/iH05Z4GoRaio2mxWfpnqs98+mp9WpzZ8OsVfxm6QwkE8Ch5jujk3ajq6dLWhjglX4nMS1mCp3R8l7xAjdwsTZhuabnMteDOli+kFiEKtskYZ9NH8IhZyIefCFy0Y7GqORVRiO07hjDk/FLNZjq2wOcXhnGfeLKNmgdzLXFJX+vRM951TgdG/c4Kk9c0Jpoqrmq9/HmXUS9xhifHJeBkAAfm1lP/GBzlyxaX/VZj2j6mqBmhavdf8WAmtPwBa4Xjw+AYXM3mcmiVYEuoIS2Xz3LbtuNeqeiLNAKOlPVpnki0a/OPjuTTIpq9Ku2yJRWYLbH5YRjkrVrk7SlOApBWUZFfJ2YaqhxY780XmG4xdD8cBprmURqoXS1imF3Bh5fMTJIf6PkineS8j1KABJ9jOrloNHetCIvtsinUrRJ1bTAEAImwLm0lwK7lE/Sn0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
