travis:
  secure:
    BINSTAR_TOKEN: CXNwblrm3gfmdSqg4oAGhIp9R6oJBXFOwLsy1qu7OTLkXsbOWe1erfYh8uLAsbEOAygmglU19zc2OYc78MDUjjKMbvJe+l8/3HttgpHnbTPyEDJfv+rL7PW0Juz35P3E2uVNT8jLBnwRLXx5UVikI2bjEGxfrrWNgaXzZTAVpH4TyFKyrA3QDm74nYB/MgdtmGKOf0VojI8nXSRJrCwTB7IwcDu7cM9Ftir+zyIXRJ+aQYYu7/S0G8INTdJKhrtxtBHHfkdotIrfrBD42GR4+rOrOEg6jpy37QaIcyom1IRvfkr22Rnsn+6oJfLNrh5yqpZ+ZfLVB0eSMZzjffsrf0NHr3eAWDzHReSo3w1cmrjdKg9pXtgG1onoECknF/CuVh0ErFOP2Kg8XhdtCSda+FOY4TYkZXZjLuTikV08oKD1l+pK6HKf+jITtO6yrYMuGNtigh11Fv2tEpDavdcFKzJZur4FGFcYX0Kp/D7dJ/A0JsJtdxgKY/6VAxDkbqzxtidN+TwbhiEbJ0IfAl7FKuBU9zGIGBUfnbHahm/czpnHmlnyOa8SZbzgknao692EJwtOH6unsdN+ZNcAw7muYz98W/aD0S1AZLPCyYCjIujxPjBwxNdTYN02aRN7S9DwycS/nc20IXBP6bIbDUqzUmI2hLpzpO0lZrcipGcuczk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
