travis:
  secure:
    BINSTAR_TOKEN: UY52yjnFZJgXk3jQavHBbK7OnGQp9BObDDuqGjMjGau6MHIBEbp6LyukQi39YukOkaXOAqT/NrfNEevd9lBbXaMyNpGcCwXhyr6o8xRpL3PApxY+23c97UXxM7U6ie11k31vxaJLZnb3MTg6MkMx1k4S550Ien00i0PjVyT0lLHIwyConKAdmAlrUyApjuo2mYCbTOGjMEuNY+1pM+1SdC7D8XovcmvbeAlVitwBvX1ZAK+Ft3WBNBfVkMYu0XxRI9XVt7J1AoL5nhixDVJDdCvRcBinrnqOSOywgioTSWxmrMPL0DzIsUtnmn0ZyzwPJ3l9YocRbPecSwUTNIRTZKp09jJxK/2I4b3CaTKMhj/I96WHwHZHOzh7UhsPLZzWCsSMp/HnPt5Flxq4e21q/MK+fUPSZHCL8cO2QU6ka/MMXav9PiWh1uduWp0F0gMa308hjf/P8qRvjFWLlVNHYehj9+mKSbBLuwz/ev3a6p1o69R4cbK8RL86kkLYj+6qgrFkYXHWN7+VXizXPpjOPlEJdPIbE5Lu9VszyXcBfIt3S+FLPN04obYoLjqbHjhc5aHgLVjBRQKLvhzue1C0TyU5Qbd66pC59cnBhIhWQ09NqmY6OjG5EE6n2FDW95dH5wQcFXU1NampfRVjMEHabzgpRtbaqiw4MiDtplEoxic=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
